(function(){var f,k=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},aa=function(a){if(k(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&k(a))return a;return null},l=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},m=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a},q=function(a,b,c,d){d=d||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)};var x=function(a,b){function c(){}c.prototype=b.prototype;a.D=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Fa=function(a,c,g){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var y=["-ms-","-moz-","-webkit-",""],z=function(a,b,c){for(var d,e,g=0;g<y.length;++g)d=y[g]+b,e=""+c,a.style.setProperty(d,e)};var C=function(a,b,c){if(c){var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c)}else d=document.createEvent("Event"),d.initEvent(a,!0,!0);b.dispatchEvent(d);return d},ba=function(a,b){setTimeout(function(){C("autoplayended",a,b)},0)},ca=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var da=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var ea=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},D=function(a){this.m=a;this.s=null;this.Ea=!0;this.M=!1};
D.prototype.play=function(a,b,c){if(this.m.frameCount&&null==this.s){b=b||"forwards";if(c){var d=Math.floor(a/c);a=c}else d=this.m.frameCount,a/=d;var e=[],g=ea(this.m);c=g;for(var p=0;p<d;p++){if(0<p||!this.Ea)c=E(c+F(b,1),this.m.frameCount);e.push(c)}b=function(){if(e.length){var a=e.shift();this.M=!0;this.m.goToFrame(a+1);this.M=!1;var b=this.m;C("frameautoplayed",b,{id:a+1||b.currentIndex})}else this.stop(!0),this.m.goToFrame(g+1)}.bind(this);this.s=setInterval(b,a);setTimeout(b)}};
D.prototype.stop=function(a){!this.M&&this.s&&(clearInterval(this.s),ba(this.m,{completed:!!a}),this.s=null)};
var fa=function(a){var b=document.getElementById("pagedeck");b=b&&b.hasAttribute("type-extension")?document.createElement("gwd-image"):document.createElement("img","gwd-image");b.setAttribute("source",a);return b},H=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(fa(da(a[c])))}return b},I=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];if("img"==e.tagName.toLowerCase()&&"gwd-image"==e.getAttribute("is")||"gwd-image"==e.tagName.toLowerCase())null!=
b?e.setAttribute("scaling",b):e.removeAttribute("scaling")}},ha=function(a,b){var c=b.length;b=b.splice(0,c);for(var d,e=0;e<c;e++)d=b[e],"frameshown"==d?C(d,a,{id:a.currentIndex}):C(d,a)},F=function(a,b){return"left"==a||"backwards"==a?-b:b},E=function(a,b){return(a%b+b)%b},ia=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")).forEach(function(a){a.pause()})},ja=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")).forEach(function(a){a.play()})};var K=function(){};x(K,HTMLElement);f=K.prototype;f.createdCallback=function(){this.frames=[];this.b=null;this.a=0;this.l=1;this.v=new D(this);Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.na.bind(this)});Object.defineProperty(this,"frameSnapInterval",{enumerable:!0,get:this.qa.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.pa.bind(this)});this.ga=this.hasAttribute("pause-front-media");this.ha=this.hasAttribute("resume-next-media")};
f.attributeChangedCallback=function(a){switch(a){case "pause-front-media":this.ga=this.hasAttribute("pause-front-media");break;case "resume-next-media":this.ha=this.hasAttribute("resume-next-media")}};f.getFrame=function(a){if(0!=this.a)return this.frames[a-1]};f.gwdLoad=function(){};f.gwdIsLoaded=function(){return!0};f.goToFrame=function(a,b){this.stopRotation();0!=this.a&&(a>this.a?a=this.a:1>a&&(a=1),this.Z(a,b))};f.Z=function(a){this.b=a-1};
var L=function(a,b,c,d){if(null!=a.b){var e=E(a.b+F(b,a.l||1),a.l*Math.ceil(a.a/a.l));null!=d&&!d&&("forwards"==b&&e<a.b||"backwards"==b&&e>a.b)||a.goToFrame(e+1,c||"slide")}};f=K.prototype;f.goBackwards=function(a,b){return L(this,"backwards",a,b)};f.goForwards=function(a,b){return L(this,"forwards",a,b)};f.rotateOnce=function(a,b){this.v.play(a||0,b)};f.stopRotation=function(){this.v.stop()};f.na=function(){return 0<this.a?this.b+1:void 0};f.qa=function(){return this.l};f.pa=function(){return this.a};var M=function(a,b){return a.x*b.x+a.y*b.y},O=function(a,b){return N(b,M(a,b))},N=function(a,b){return P(a.x*b,a.y*b)},P=function(a,b){return{x:a,y:void 0!==b?b:a}};var Q=function(){};x(Q,K);
Q.prototype.createdCallback=function(){Q.D.createdCallback.call(this);this.N=!1;this.O=this.c=null;if(this.Y=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);this.o=P(0);var a=document.createElement("gwd-gesture");a.className="gesture";this.A=a;this.j=!1;this.f=null;this.ca=this.xa.bind(this);this.ea=this.za.bind(this);this.aa=this.va.bind(this);this.ba=this.wa.bind(this);this.da=this.ya.bind(this);this.V=this.sa.bind(this);this.ma=this.Ca.bind(this);this.la=this.Ba.bind(this);
this.ka=this.Aa.bind(this);this.X=this.ta.bind(this);this.fa=this.ua.bind(this);this.I=C.bind(null,"firstinteraction",this);this.R=!1;this.B=[];this.u=ha.bind(null,this,this.B);this.ia=this.ja=this.G=this.T=this.S=0;this.L=1;this.H=[];this.K=0;this.Da=.7;this.C=0;this.F=!1;this.P=P(0);this.J=P(0);this.h=null;this.g=this.$=-1;this.W=[];this.w=P(-1,-1);a="y"==this.getAttribute("swipe-axis");this.i=P(a?0:1,a?1:0);Object.defineProperty(this,"firstVisibleFrameIndex",{enumerable:!0,get:this.oa.bind(this)});
Object.defineProperty(this,"lastVisibleFrameIndex",{enumerable:!0,get:this.ra.bind(this)})};
Q.prototype.attachedCallback=function(){var a=this.A;a.addEventListener("pointerover",this.ea,!1);a.addEventListener("pointerout",this.ca,!1);a.addEventListener("pointermove",this.aa,!1);a.addEventListener("track",this.ma,!1);a.addEventListener("trackend",this.la,!1);a.addEventListener("tap",this.ka,!1);this.addEventListener("frametap",this.X,!1);this.addEventListener("swipefinished",this.U,!1);this.addEventListener("transitionend",this.u,!1);this.addEventListener("webkitTransitionEnd",this.u,!1);
if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var b=(a=aa(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&this.gwdLoad()}};
Q.prototype.detachedCallback=function(){var a=this.A;a.removeEventListener("pointerover",this.ea,!1);a.removeEventListener("pointerout",this.ca,!1);a.removeEventListener("pointermove",this.aa,!1);a.removeEventListener("track",this.ma,!1);a.removeEventListener("trackend",this.la,!1);a.removeEventListener("tap",this.ka,!1);this.removeEventListener("frametap",this.X,!1);this.removeEventListener("swipefinished",this.U,!1);this.removeEventListener("transitionend",this.u);this.removeEventListener("webkitTransitionEnd",
this.u)};
Q.prototype.attributeChangedCallback=function(a){Q.D.attributeChangedCallback.call(this,a);switch(a){case "images":this.frames=H(this.getAttribute("images"));R(this);S(this);break;case "scaling":I(this.frames,this.getAttribute("scaling"));break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":T(this);S(this);break;case "transition-duration":case "exit-urls":case "autoplay-duration":case "autoplay-step-interval":U(this);break;case "frame-width":case "frame-height":case "frame-snap-interval":case "num-frames-to-display":U(this);S(this);
break;case "disable-gesture":case "offset":case "start-frame":case "swipe-threshold-ratio":case "swipe-committed-threshold-ratio":S(this)}};
var U=function(a){var b=l(a,"num-frames-to-display",1),c=l(a,"frame-snap-interval",1),d=l(a,"transition-duration",600),e=l(a,"frame-width",-1),g=l(a,"frame-height",-1),p=m(a,"autoplay-duration",3E3),h=m(a,"autoplay-step-interval",0);a.w.x=e;a.w.y=g;-1!=M(a.w,a.i)?b=-1:0<b&&c>b&&(c=b);e=[];if(g=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):""){g=g.split(",");for(var r=0;r<g.length;r++)e[r]=g[r].trim()}a.W=e;a.g=b;a.l=c;a.G=d;a.S=p;a.T=h},S=function(a){var b=P(a.clientWidth,a.clientHeight);
a.h&&(b.y-=36,a.O.style.height=b.y+"px");var c=a.i,d=N(c,l(a,"offset",0)),e=m(a,"swipe-threshold-ratio",.1),g=m(a,"swipe-committed-threshold-ratio",.5),p=a.g,h=a.w;h=P(-1==h.x?b.x:h.x,-1==h.y?b.y:h.y);if(a.hasAttribute("offset")){a:{var r=h.x;var n=h.y;var w=a.frames,A=!0;if(a.hasAttribute("clamp-frame-size-to-image")){var u=a.getAttribute("clamp-frame-size-to-image");"true"==u?A=!0:"false"==u&&(A=!1)}if(A&&(u=a.hasAttribute("scaling")?a.getAttribute("scaling"):"contain",((A="contain"==u)||"none"==
u)&&0!=r&&0!=n)){var G=-1;u=-1;for(var la=w.length,J=0;J<la;J++){var t=w[J];if(("img"!=t.tagName.toLowerCase()||"gwd-image"!=t.getAttribute("is"))&&"gwd-image"!=t.tagName.toLowerCase())break a;var v=t.assetWidth?t.assetWidth:t.naturalWidth,B=t.assetHeight?t.assetHeight:t.naturalHeight;0<v&&0<B&&(A?v/B<r/n?(t=v/B*n,v=n):(t=r,v=B/v*r):(t=v,v=B),G=Math.max(G,t),u=Math.max(u,v))}r=-1!=G?Math.min(r,G):r;n=-1!=u?Math.min(n,u):n}}1==c.x?h.x=r:h.y=n}1<p&&(n=N(c,p-1),n=P(n.x*d.x,n.y*d.y),p=O(P((b.x-n.x)/p,
(b.y-n.y)/p),c),p.x&&(h.x=p.x),p.y&&(h.y=p.y));p=l(a,"start-frame",2<a.g?1+Math.ceil(a.g/2-1):1);r=a.hasAttribute("disable-gesture");n=O(P(h.x+d.x,h.y+d.y),c);w=1+2*Math.floor((M(c,b)-M(c,h))/(2*M(c,n)));if(1>w||!isFinite(w))w=1;b=P((b.x-h.x)/2,(b.y-h.y)/2);0<a.g&&0==a.g%2&&(d=O(P(h.x+d.x,h.y+d.y),c),b.x-=.5*d.x,b.y-=.5*d.y,w+=1);a.J=h;a.P=b;a.L=w;a.C=M(n,a.i);a.j=r;a.ja=M(h,c)*e;a.ia=M(h,c)*g;e=O(b,P(c.y,c.x));for(d=0;d<a.a;d++)g=a.frames[d].style,g.left=e.x+"px",g.top=e.y+"px",g.width=h.x+"px",
g.height=h.y+"px",e.x+=n.x,e.y+=n.y;a.o=P(0);a.c&&(V(a,0,0,0),c=O(b,c),a.c.style.left=c.x+"px",a.c.style.top=c.y+"px");a.b=null;a.goToFrame(p,"none")};f=Q.prototype;f.gwdIsLoaded=function(){return this.N};f.gwdLoad=function(){if(!this.N&&!this.c){if(this.Y)var a=H(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;R(this)}};
f.goBackwards=function(a,b){return Q.D.goBackwards.call(this,a,null!=b?b:!1)};f.goForwards=function(a,b){return Q.D.goForwards.call(this,a,null!=b?b:!1)};
f.Z=function(a,b){var c=a-1;c-=c%this.l;c+=Math.floor((this.l-1)/2);0>c?c=0:c>=this.a&&(c=this.a-1);if(1<this.g){a=W(this,c);var d=a+this.g-1;1>a&&(c+=1-a);d>this.a&&(c-=d-this.a)}a=c;null!=this.b&&this.b!=a&&(this.ga&&ia(this.frames[this.b]),this.ha&&ja(this.frames[a]));a=this.b;this.b=c;c=N(this.i,-this.C*this.b);V(this,"none"!=b?this.G:0,c.x,c.y);this.o=c;if(this.K)for(b=Math.floor((this.L-1)/2),c=0;c<this.L;c++)if(d=this.b-b+c,!(0>d||d>=this.a||this.H[d]||(this.H[d]=!0,--this.K))){this.B.push("allframesviewed");
break}a!=this.b&&(X(this,this.b+1),this.B.push("frameshown"),this.B.push("swipefinished"));this.R||this.u()};
var V=function(a,b,c,d){a.R=0<b;z(a.c,"transition","transform "+b+"ms");z(a.c,"transform","translate3d("+c+"px,"+d+"px,0)")},R=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.h=null;a.c&&(a.c.removeEventListener("pageload",a.fa,!1),a.c.removeEventListener("mouseover",a.da,!0),a.c.removeEventListener("mouseout",a.ba,!0),a.c.removeEventListener("click",a.V,!0));var b=a.frames,c=document.getElementById("pagedeck");c=c&&c.hasAttribute("type-extension")?document.createElement("gwd-page"):
document.createElement("div","gwd-page");for(var d,e=0;e<b.length;++e)d=b[e],z(d,"user-select","none"),d.classList.add("frame"),c.appendChild(d);ca(c,c.gwdLoad.bind(c));a.c=c;c.className="container";a.c.addEventListener("pageload",a.fa,!1);a.c.addEventListener("mouseover",a.da,!0);a.c.addEventListener("mouseout",a.ba,!0);a.c.addEventListener("click",a.V,!0);I(a.frames,a.getAttribute("scaling"));a.a=a.frames.length;b=document.createElement("div");a.O=b;b.className="matte";b.appendChild(c);a.appendChild(a.O);
a.appendChild(a.A)};Q.prototype.U=function(){z(this.c,"transition","transform 0ms")};Q.prototype.ua=function(a){a.target===this.c&&(this.N=!0,this.K=this.a,this.H=[],U(this),T(this),S(this),C("allframesloaded",this),this.hasAttribute("autoplay")&&this.v.play(this.S,"forwards",this.T),C("ready",this))};Q.prototype.rotateOnce=function(a,b){this.v.play(a||this.G,b)};
var ka=function(a,b){var c=a.a;if(c){var d=a.b;b=Y(a,b);a.goToFrame(b+1);d!=b&&(0==b?C("reachleftend",a):b==c-1&&C("reachrightend",a))}},T=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.h;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.h=document.createElement("gwd-gallerynavigation"),a.h.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.h)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.h),a.h=null);a.h&&(q(a,"navigation-highlight",a.h,"highlight"),
q(a,"navigation-thumbnails",a.h,"use-thumbnails"))},Y=function(a,b){var c=a.b;Math.abs(b)>a.ja&&(c=0>b?c+a.l:c-a.l);0>c?c=0:c>=a.a&&(c=a.a-1);return c},X=function(a,b){a.$!=b&&(a.$=b,C("frameactivated",a,{id:b||a.currentIndex}))};
Q.prototype.Ca=function(a){if(!this.j&&(this.I&&(this.I(),this.I=null),!this.F))if(this.stopRotation(),a=M(P(a.dx,a.dy),this.i),X(this,Y(this,a)+1),Math.abs(a)>this.ia)ka(this,a),this.F=!0;else{if(0<a&&0===this.b||0>a&&this.b===this.a-1)a-=a*this.Da;V(this,0,this.o.x+this.i.x*a,this.o.y+this.i.y*a)}};Q.prototype.Ba=function(a){this.j||(this.F?this.F=!1:ka(this,M(P(a.dx,a.dy),this.i)))};
var Z=function(a,b){var c=a.getBoundingClientRect();b=P(b.clientX-c.left,b.clientY-c.top);c=a.i;var d=P(c.y,c.x);c=M(d,b);var e=M(d,a.P);d=M(d,a.J);if(c<e||c>e+d)return null;c=a.i;b=M(c,b)-M(c,a.o)-M(c,a.P);c=Math.floor(b/a.C);return 0>c||c>=a.a||b%a.C>M(a.i,a.J)?null:c};f=Q.prototype;
f.Aa=function(a){if(!this.j){this.stopRotation();var b=this.A;var c=this.c;var d=a.clientX,e=a.clientY,g=b.style["pointer-events"];b.style["pointer-events"]="none";d=c.ownerDocument.elementFromPoint(d,e);b.style["pointer-events"]=g;if(b=d)if(b=d,c.contains&&1==b.nodeType)b=c==b||c.contains(b);else if("undefined"!=typeof c.compareDocumentPosition)b=c==b||!!(c.compareDocumentPosition(b)&16);else{for(;b&&c!=b;)b=b.parentNode;b=b==c}c=b?d:null;(b=!c)||(b=a.clientX,g=a.clientY,d=!1,"gwd-taparea"===c.tagName.toLowerCase()&&
(d=c.ownerDocument.createEvent("Event"),d.initEvent("action",!0,!0),d.clientX=b,d.clientY=g,d=!c.dispatchEvent(d)),b=!d);b&&(a=Z(this,a),null!=a&&C("frametap",this,{element:this.frames[a],id:a+1}))}};f.ta=function(a){(a=a.detail&&a.detail.id)&&(a=this.W[a-1])&&!C("frameexit",this,{url:a}).detail.handled&&window.open(a)};f.xa=function(){this.j||null==this.f||(C("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),this.f=null)};
f.za=function(a){this.j||(a=Z(this,a),a!=this.f&&(null!=this.f&&C("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),null!=a&&C("framemouseover",this,{element:this.frames[a],id:1+a}),this.f=a))};f.va=function(a){this.j||(a=Z(this,a),a!=this.f&&(null!=this.f&&C("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),null!=a&&C("framemouseover",this,{element:this.frames[a],id:1+a}),this.f=a))};
f.ya=function(a){this.j&&a.target.classList.contains("frame")&&C("framemouseover",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};f.wa=function(a){this.j&&a.target.classList.contains("frame")&&C("framemouseout",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};f.sa=function(a){this.j&&a.target.classList.contains("frame")&&C("frametap",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};var W=function(a,b){return 1+(void 0!==b?b:a.b)-Math.floor((a.g-1)/2)};
Q.prototype.oa=function(){if(0<this.g&&0<this.a)return Math.max(1,W(this))};Q.prototype.ra=function(){if(0<this.g&&0<this.a)return Math.min(this.a,W(this)+this.g-1)};document.registerElement("gwd-swipegallery",{prototype:Q.prototype});}).call(this);
